# commands to specify testing environments
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: 3.9
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
    - python: pypy3
  allow_failures:
    - python: nightly
    - python: pypy3

branches:
  only:
    - master
    - /^[0-9].+$/

# command to install dependencies
install:
  - python -m pip install --upgrade pip
  - pip install -r test-requirements.txt
  - python -m pip install mypy
  - python -m pip install flake8
  - mypy --version

# command to run tests
script:
  - python --version
  - python -m unittest discover -p '*_test.py'
  - mypy --namespace-packages --ignore-missing-imports --follow-imports=silent nion/ui/Window.py
  - flake8 --max-line-length=160 nion/ui/Window.py
