package:
  name: 'nionui'
  version: '0.4.5'

source:
  git_rev: 0.4.5
  git_url: https://github.com/nion-software/nionui.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False
  entry_points:
    - nionui = nion.ui.command:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.7
    - nionutils >=0.3.21,<0.4.0
    - numpy
    - imageio

test:
  imports:
    - nion.ui
    - nion.ui.test

about:
  home: https://github.com/nion-software/nionui
  license: Apache-2.0
  summary: Nion UI classes.
  description: "A library of useful UI objects."

extra:
  recipe-maintainers:
    cmeyer
